# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfuncionario', '0003_remove_inscricao_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='validacao',
            field=models.BooleanField(default=False, verbose_name='Consistente'),
        ),
    ]
